### ISSUE TITLE
Feature Request: Light mode

### ISSUE THREAD

**Issue by RubenHetKonijn** [tmpim/KristWeb2#54]
Everything on my computer is set to light mode, everything matches except Kristweb, I can't find the light mode option if there is one, please add this :)

**Comment by Lemmmy** [comment]
PR's welcome, but this would be too much development work

**Comment by Lemmmy** [comment]
I've had a further look at this (for a completely different project with a similar codebase, actually), and unfortunately I don't think this is going to be trivial, or even possible. ant-design v4 does not make it simple to dynamically switch the theme, unless you are using Umi + antd-pro, which KristWeb does not.

Achieving this would require either:
- Finding a tidy way to compile multiple LESS entrypoints with webpack, while still supporting hot-reloading and proper bundling. I spent a whole day on this yesterday, and ended up giving up, as none of the supposed solutions worked.
- Compiling both themes into the same CSS file, and using a document selector to switch them. This is not really possible either without a pre-processing step that prepends selectors to the ant themes when imported, but even that would cause the theme overrides to break.

The main root cause of the problem is create-react-app, in its present state, has not made it easy to separately compile multiple CSS chunks while still supporting CSS modules. Many components in the app depend directly on smaller CSS files, which themselves depend on the main one. Everything would have to be restructured, and that's assuming all the other problems are addressed.

Those are the technical barriers; it doesn't even address the fact that developing two themes side-by-side for an app of this size isn't a simple task, and would not just be style changes, but potentially also code changes. For the people that offered to help - thank you, but the only ways to solve these are far too hacky, and I do not want to accept anything hacky for this kind of thing.

I will continue watching developments in this field and see if I eventually solve it in any other projects, but this is extremely low priority for me and the project right now, so sorry, but I do not expect to ever implement this for KristWeb.

You may have luck inverting the colours with an extension such as Dark Reader ([Chrome](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related?hl=en), [Firefox](https://addons.mozilla.org/en-GB/firefox/addon/darkreader/), [Edge](https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc)), may require some settings tweaking though.
