### ISSUE TITLE
Names list on address page shows name registration date and not transfer date

### ISSUE THREAD

**Issue by Kan18** [tmpim/KristWeb2#58]
1. Visit https://krist.club/network/addresses/k64shopdmi (or any other address that has a name which it did not originally own)
2. Look at Names 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/24967425/161429754-3129abd5-b880-4624-b955-d75e1463c842.png">
I expected to see "3 months ago" instead of "3 years ago" there, since the name was _received_ three months ago

If the "3 years ago" is intended there it might be worth prepending "Registered" to the duration there so it would look like "Registered 3 years ago"

**Comment by Lemmmy** [comment]
Good catch - if I remember correctly it says 'received' instead of 'purchased' if the owner is different too the original owner, but it's a little harder without additional requests to figure out the transfer date.

https://github.com/tmpim/KristWeb2/blob/731db261526a45c1d8bf068ed132f22d2fafc469/src/pages/addresses/NameItem.tsx#L21-L32

This may require an API change and a DB migration, I'll look into it.

**Comment by Kan18** [comment]
there is a bug with this: Purchased and Registered got mixed up

**Comment by Lemmmy** [comment]
Fixed in 2940a18e - thank you!
