### ISSUE TITLE
Feature: Recurring payments to wallets

### ISSUE THREAD

**Issue by EmmaKnijn** [tmpim/KristWeb2#59]
This is a feature request. You should have an option to have recurring payments from your own wallet to another wallet (say a subscription based shop).

**Comment by Lemmmy** [comment]
In its current state this seems like a feature better suited for a user program, or some other third-party service outside of KristWeb.  KristWeb itself cannot implement this without the help of another service, because [periodic background sync](https://developer.chrome.com/articles/periodic-background-sync/) is still WIP and not widely supported. 

I ran into a similar problem with [KanjiSchool](https://github.com/Lemmmy/KanjiSchool), where we wanted to have hourly notifications for the user when they had new reviews available. But KanjiSchool has no server component at all - it is purely a frontend for an entirely third-party API, so push notifications would need to be used.

I'm not *entirely* opposed to Krist having some native functionality for recurring payments but I also don't think it has a responsibility to have such functionality either. It sounds like a large can of worms to open for little gain, when I personally don't support the concept of recurring payments in the first place.
